version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo:3
    ports:
      - "27017:27017"
    volumes:
      - dbvolume:/data/db
volumes:
  dbvolume: